### ISSUE TITLE
Add a means to test a subset of chunks (which could be one chunk)

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/dazzle#38]
## Is your feature request related to a problem? Please describe

Inspecting how a new test is running requires building all chunks and running all tests, which makes for a long dev loop.

## Describe the behaviour you'd like

Provide a means to build and run a subset of chunks (which could also be a single chunk)

## Describe alternatives you've considered

Create a new branch to do testing from main, just with the chunks I want to build and test.
Once the tests are working, copy them into yet another new branch created from main.

## Additional context

This should help folks more easily test, which will hopefully encourage more authoring of tests.

**Comment by princerachit** [comment]
Dazzle already has an ignore flag at project level that can be used to ignore chunks. This issue is requesting same feature through `addition` instead of `negation`.

e.g. command

```console
dazzle project ignore dep-cacert-update
```

results in the following section being added to `dazzle.yml` file. 
```yaml
combiner:
  combinations: []
ignore:
- dep-cacert-update
````
While building, the chunks mentioned here are ignored.

https://github.com/gitpod-io/dazzle/blob/87d48f997df4ce37c97cc4169b4908e4ad2939a7/pkg/dazzle/project.go#L200-L202

I think it is better to reuse this flag than adding another one. what are your thoughts @kylos101 @Furisto ?

**Comment by Furisto** [comment]
@princerachit I was not aware of that flag. That's great!. We could write a simple script like 
`for file in $(ls chunks) ; do dazzle project ignore "$file"; done`
to add every chunk. Just have to remove the one that you are currently working on. 

When I do that and run dazzle-up.sh the build process seems to be stuck in some kind of endless loop where it builds the same thing over and over again. Looks almost like what we have seen in some prebuilds a while ago. This is my dazzle.yaml (should only build go chunk)

```
combiner:
  combinations:
  - name: base
    ref: []
    chunks:
    - dep-cacert-update
    - tool-docker
    - tool-tailscale
  - name: c
    ref:
    - base
    chunks:
    - lang-c
  - name: clojure
    ref:
    - base
    chunks:
    - lang-clojure
  - name: full
    ref:
    - base
    chunks:
    - lang-c
    - lang-clojure
    - lang-go:1.17.5
    - lang-java:11
    - lang-node:16.13.2
    - lang-python
    - lang-ruby:2.7
    - lang-rust
    - tool-brew
    - tool-nginx
    - tool-nix:2.6.0
  - name: full-vnc
    ref:
    - full
    chunks:
    - tool-vnc
  - name: go
    ref:
    - base
    chunks:
    - lang-go:1.17.5
  - name: node
    ref:
    - base
    chunks:
    - lang-node:17.4.0
  - name: node-lts
    ref:
    - base
    chunks:
    - lang-node:16.13.2
  - name: python
    ref:
    - base
    chunks:
    - lang-python
  - name: ruby-2
    ref:
    - base
    chunks:
    - lang-ruby:2.7
  - name: ruby-3
    ref:
    - base
    chunks:
    - lang-ruby:3
  - name: rust
    ref:
    - base
    chunks:
    - lang-rust
  - name: dotnet
    ref:
    - full
    chunks:
    - tool-dotnet
  - name: postgresql
    ref:
    - full
    chunks:
    - tool-postgresql
  - name: mysql
    ref:
    - full
    chunks:
    - tool-mysql
  - name: mongodb
    ref:
    - full
    chunks:
    - tool-mongodb
  - name: java-11
    ref:
    - base
    chunks:
    - lang-java:11
  - name: java-17
    ref:
    - base
    chunks:
    - lang-java:17
  envvars:
  - name: PATH
    action: merge-unique
  - name: HOME
    action: use-last
ignore:
- dep-cacert-update
- lang-c
- lang-clojure
- lang-java
- lang-node
- lang-python
- lang-ruby
- lang-rust
- tool-brew
- tool-docker
- tool-dotnet
- tool-mongodb
- tool-mysql
- tool-nginx
- tool-nix
- tool-postgresql
- tool-tailscale
- tool-vnc
```
