### ISSUE TITLE
Support multiple base images.

### ISSUE THREAD

**Issue by aaqaishtyaq** [gitpod-io/dazzle#53]
I have a project setup that builds dev container images similar to Gitpod's workspace images. 
Currently, I am using `ubuntu:20.04` as a base image but want to build some images with `ubuntu:22.04`. 
Instead of creating all the images with the newer base image, I want something like:

```yaml
  - name: pyspark-next
    ref:
      - base-22.04
    chunks:
    - lang-nodejs:16.13.0
    - lang-python
    - lang-java:11
```
